services:
  db:
    image: postgres:16-alpine
    container_name: time_tracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: time_tracker_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: api
      dockerfile: TimeTrackingApp.Api/Dockerfile
    container_name: time_tracking_api
    restart: always
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=time_tracker_db;Username=postgres;Password=password123"
    ports:
      - "5163:8080"
  client:
    build:
      context: client
      dockerfile: dockerfile
      args:
        VITE_API_URL: /api
        VITE_APP_NAME: TimeTracker
    container_name: time_tracker_client
    restart: always
    depends_on:
      - api
    ports:
      - 80:80

volumes:
  pgdata: